# Generated by Django 2.2.5 on 2019-10-01 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='app/static/galaxias/img1.jpeg', upload_to='app')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Que_tipo_de_interacción_ves', models.CharField(choices=[('A', 'Alta'), ('B', 'Baja'), ('C', 'Ninguna')], default='A', max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Imagen')),
            ],
        ),
    ]
