# Generated by Django 2.2.1 on 2019-09-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_text',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AddField(
            model_name='choice',
            name='Que_tipo_de_interacción_ves',
            field=models.CharField(choices=[('A', 'Alta'), ('B', 'Baja')], default='A', max_length=200),
        ),
        migrations.AddField(
            model_name='choice',
            name='image',
            field=models.ImageField(default='galaxias/tailandia.jpg', upload_to='galaxias'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
