# Generated by Django 2.2.5 on 2019-10-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='image',
            field=models.ImageField(default='static/Scatter_Mh_vs_Ms.png', upload_to='encuesta'),
        ),
    ]
