# Generated by Django 2.2.5 on 2019-10-30 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0002_auto_20191029_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='image',
            field=models.ImageField(default='static/Scatter_Mh_vs_Ms.png', upload_to=''),
        ),
    ]
