# Generated by Django 2.2.5 on 2019-10-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0004_auto_20191029_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='image',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='name',
        ),
        migrations.AddField(
            model_name='imagen',
            name='cover',
            field=models.ImageField(default='NOSE', upload_to='images/'),
        ),
    ]
