# Generated by Django 2.2.5 on 2019-10-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0005_auto_20191030_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='cover',
            field=models.ImageField(default='RdCeL.png', upload_to='images/'),
        ),
    ]
