# Generated by Django 2.2.5 on 2019-10-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0007_auto_20191030_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
