# Generated by Django 2.2.5 on 2019-10-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0008_auto_20191030_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='imagen',
        ),
        migrations.AddField(
            model_name='choice',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
