# Generated by Django 2.2.5 on 2019-10-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0009_auto_20191030_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
    ]
