# Generated by Django 2.2.1 on 2019-10-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0010_auto_20191030_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='cover',
            field=models.ImageField(default='static/Scatter_Mh_vs_Ms.png', upload_to='static/'),
        ),
    ]
