# Generated by Django 2.2.5 on 2019-11-24 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0011_auto_20191030_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='cover',
        ),
        migrations.AddField(
            model_name='choice',
            name='imagen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encuesta.Images'),
        ),
    ]
