# Generated by Django 2.2.5 on 2019-11-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0012_auto_20191124_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='voto',
            field=models.CharField(choices=[('A', 'Alta'), ('B', 'Baja'), ('C', 'Media')], max_length=200),
        ),
    ]
