# Generated by Django 2.2.1 on 2019-11-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0016_auto_20191126_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='voto',
            field=models.CharField(choices=[('A', 'Alta'), ('B', 'Baja'), ('M', 'Media')], max_length=200),
        ),
    ]
